/* ==========================================================================
   AET — DONNÉES PARTAGÉES (source unique : modules, niveaux, prompts, vidéos)
   Utilisé par : formation-ia-prompting.html, programme.html, cours.html,
   dashboard.html, prompts.html, videos.html, quiz.js
   ========================================================================== */

const AET_MODULES = [
  {n:1,niv:1,titre:"Découvrir l'intelligence artificielle",objectif:"Comprendre ce que sont l'IA, l'IA générative et les assistants conversationnels.",retenir:["Définition simple de l'IA","IA générative et exemples","Texte, image, audio, vidéo et code","Limites, erreurs et hallucinations","Pourquoi vérifier les informations"],prompt:"Explique l'intelligence artificielle simplement, puis donne trois exemples concrets de son utilisation dans la vie quotidienne.",exercice:"Reformule ce prompt en 3 versions : une pour un enfant, une pour un débutant, une pour un usage professionnel.",ressource:{titre:"Fondamentaux officiels de l'IA",url:"https://openai.com/academy/ai-fundamentals/"}},
  {n:2,niv:1,titre:"Prendre en main un assistant IA",objectif:"Savoir démarrer une conversation, donner une consigne, demander une correction et poursuivre un échange.",retenir:["Interface et conversation","Question vs instruction","Contexte","Pièces jointes et multimodalité","Itération"],prompt:"Tu es mon assistant d'apprentissage. Pose-moi 5 questions pour comprendre mon objectif, puis construis un plan d'apprentissage sur 7 jours.",exercice:"Fais résumer un texte de ton choix par l'IA, puis demande-lui 3 variantes du résumé.",ressource:{titre:"Introduction au prompt engineering",url:"https://academy.openai.com/public/videos/introduction-to-prompt-engineering-2025-02-13"}},
  {n:3,niv:1,titre:"Poser des demandes claires",objectif:"Passer d'une demande vague à une instruction exploitable.",retenir:["Objectif","Contexte","Public","Ton","Format","Contraintes"],prompt:"Je veux une publicité pour une formation en IA. Pose-moi d'abord les questions nécessaires pour obtenir les informations manquantes, puis rédige la publicité.",exercice:"Transforme 5 demandes vagues de ton quotidien en instructions complètes (objectif + contexte + format).",ressource:{titre:"Maîtriser les prompts",url:"https://academy.openai.com/en/public/videos/mastering-prompts-the-key-to-getting-what-you-need-from-chatgptmastering-prompts-the-key-to-getting-what-you-need-from-chatgpt-2025-03-20"}},
  {n:4,niv:1,titre:"IA comme assistant personnel",objectif:"Utiliser l'IA pour organiser, apprendre, écrire, résumer et préparer des tâches.",retenir:["Planning","Emails","Résumé","Reformulation","Listes","Préparation de réunion"],prompt:"Organise ces tâches en planning priorisé pour aujourd'hui. Classe-les par urgence et importance, et propose une durée réaliste pour chacune.",exercice:"Transforme une liste de notes brutes en compte rendu structuré.",ressource:{titre:"Portail OpenAI Academy",url:"https://openai.com/academy/"}},

  {n:5,niv:2,titre:"Anatomie d'un bon prompt",objectif:"Construire une instruction complète et contrôlable.",retenir:["Rôle","Tâche","Contexte","Public","Contraintes","Format","Critères de qualité"],prompt:"Agis comme un expert en marketing digital. Contexte : AET prépare une formation pratique en IA destinée aux débutants francophones. Tâche : rédige une publication Facebook. Public : jeunes étudiants, salariés et entrepreneurs. Ton : professionnel, motivant et simple. Contraintes : 180 mots maximum. Format : titre, accroche, bénéfices, programme, appel à l'action.",exercice:"Réécris 5 prompts faibles en ajoutant rôle, tâche, contexte, contraintes et format.",ressource:{titre:"Guide de structure d'un prompt",url:"https://academy.openai.com/en/public/clubs/work-users-ynjqu/resources/prompting"}},
  {n:6,niv:2,titre:"Rôle, contexte et audience",objectif:"Donner à l'IA une mission et un environnement de travail précis.",retenir:["Rôles","Audience","Niveau d'expertise","Contexte métier","Informations disponibles"],prompt:"Tu es un formateur en IA. Explique le prompting à un débutant francophone qui utilise uniquement son téléphone. Utilise des exemples simples et termine par un exercice.",exercice:"Reformule la même tâche pour 3 audiences différentes (étudiant, salarié, entrepreneur).",ressource:{titre:"Formuler des demandes efficaces",url:"https://academy.openai.com/en/public/videos/mastering-prompts-the-key-to-getting-what-you-need-from-chatgptmastering-prompts-the-key-to-getting-what-you-need-from-chatgpt-2025-03-20"}},
  {n:7,niv:2,titre:"Contraintes et formats",objectif:"Contrôler longueur, style, structure et critères de sortie.",retenir:["Nombre de mots","Tableaux","Listes","Étapes","Ton","Interdictions","Critères"],prompt:"Analyse le texte fourni. Donne d'abord un résumé de 80 mots maximum, puis un tableau avec : problème, cause possible, preuve disponible, action proposée. Signale clairement ce qui reste incertain.",exercice:"Produis la même information en 5 formats différents (liste, tableau, paragraphe, étapes, résumé court).",ressource:{titre:"Exemples de formats de sortie",url:"https://academy.openai.com/en/public/clubs/work-users-ynjqu/resources/prompting"}},
  {n:8,niv:2,titre:"Itération et amélioration",objectif:"Corriger un premier résultat sans recommencer inutilement.",retenir:["Identifier le défaut","Ajouter une information","Changer le format","Demander une seconde version","Comparer"],prompt:"Évalue ta réponse précédente selon ces critères : précision, clarté, respect des contraintes et utilité. Donne une note descriptive pour chaque critère, identifie les faiblesses puis propose une version améliorée.",exercice:"Crée une version 1 d'un prompt, critique-la, puis améliore-la.",ressource:{titre:"Bonnes pratiques et itération",url:"https://academy.openai.com/public/events/prompting-with-purpose-best-practice-techniques-for-harnessing-chatgpt-d8kbsplbun"}},
  {n:9,niv:2,titre:"Décomposer les tâches complexes",objectif:"Transformer une mission importante en étapes contrôlables.",retenir:["Planification","Étapes","Entrées/sorties","Points de contrôle","Validation"],prompt:"Je veux préparer une campagne marketing. Décompose le travail en étapes. Pour chaque étape indique : objectif, informations nécessaires, livrable attendu et point de vérification.",exercice:"Décompose une étude de marché en étapes contrôlables.",ressource:{titre:"Décomposer les tâches complexes",url:"https://www-cdn.anthropic.com/084af19750155255a32ff2f267b4297924f5b666.pdf"}},
  {n:10,niv:2,titre:"Prompts réutilisables",objectif:"Créer une bibliothèque de prompts adaptables.",retenir:["Variables","Placeholders","Versions","Nommage","Documentation"],prompt:"Crée un modèle de prompt réutilisable pour [TYPE DE TÂCHE]. Utilise des champs entre crochets : [OBJECTIF], [PUBLIC], [CONTEXTE], [CONTRAINTES], [FORMAT]. Ajoute une courte notice expliquant comment le personnaliser.",exercice:"Crée 10 templates de prompts pour ton métier ou domaine.",ressource:{titre:"Templates et variables de prompt",url:"https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/prompt-templates-and-variables"}},

  {n:11,niv:3,titre:"IA pour les études",objectif:"Utiliser l'IA comme assistant pédagogique sans remplacer le travail personnel.",retenir:["Fiches de révision","Explications","Quiz","Plan d'étude","Correction","Simulation d'examen"],prompt:"Agis comme un tuteur. À partir du cours que je fournis, explique les notions difficiles avec des exemples. Ensuite crée 10 questions progressives. Ne donne pas immédiatement les réponses : attends ma tentative puis corrige-la.",exercice:"Crée une fiche de révision et 20 questions sur un sujet que tu étudies.",ressource:{titre:"Fonctions d'apprentissage et quiz (Gemini)",url:"https://support.google.com/gemini/answer/16448384?co=GENIE.Platform%3DAndroid&hl=fr"}},
  {n:12,niv:3,titre:"IA pour le travail",objectif:"Transformer des informations brutes en documents professionnels.",retenir:["Emails","Rapports","Comptes rendus","Procédures","Synthèses","Présentations"],prompt:"Transforme mes notes en compte rendu professionnel. Conserve uniquement les informations fournies. Sépare : décisions, actions, responsable, échéance et points à clarifier.",exercice:"Transforme un brief en présentation structurée.",ressource:{titre:"Ressources de travail et usage professionnel",url:"https://openai.com/academy/"}},
  {n:13,niv:3,titre:"Création de contenu",objectif:"Produire une stratégie éditoriale cohérente.",retenir:["Idées","Calendrier","Posts","Scripts","Storytelling","CTA"],prompt:"Tu es responsable éditorial. Crée un calendrier de contenu de 30 jours pour [ACTIVITÉ]. Pour chaque jour : sujet, objectif, format, accroche, idée principale et appel à l'action.",exercice:"Crée 5 scripts de Reels et 10 publications pour une activité de ton choix.",ressource:{titre:"Bibliothèque de contenus vidéo",url:"https://academy.openai.com/public/content"}},
  {n:14,niv:3,titre:"Images et direction artistique",objectif:"Écrire des prompts visuels précis et reproductibles.",retenir:["Sujet","Composition","Lumière","Décor","Style","Cadrage","Contraintes"],prompt:"Crée un prompt d'image pour une publicité AET : sujet principal, décor, composition, lumière, cadrage, style photographique, texte à éviter dans l'image et format vertical 4:5.",exercice:"Crée 4 prompts d'image : portrait corporate, flyer, produit, réseaux sociaux.",ressource:{titre:"Usages créatifs de l'IA",url:"https://openai.com/academy/"}},
  {n:15,niv:3,titre:"IA pour la vidéo",objectif:"Construire une vidéo à partir d'une idée.",retenir:["Concept","Script","Storyboard","Plans","Voix","Sous-titres","CTA"],prompt:"Transforme cette idée en vidéo de 30 secondes. Donne : accroche 0-3s, scène 1, scène 2, scène 3, voix off, texte à l'écran et appel à l'action.",exercice:"Écris le script d'une vidéo de 30 secondes pour promouvoir un service.",ressource:{titre:"Génération de vidéos (Gemini)",url:"https://support.google.com/gemini/answer/16126339?co=GENIE.Platform%3DAndroid&hl=en"}},
  {n:16,niv:3,titre:"IA pour le marketing",objectif:"Construire une campagne complète assistée par IA.",retenir:["Client cible","Proposition de valeur","Message","Canaux","Contenu","Publicité"],prompt:"Construis une campagne marketing pour [PRODUIT]. Commence par définir la cible et son problème principal. Propose ensuite le positionnement, le message central, 3 angles publicitaires, 5 contenus et un plan de test.",exercice:"Construis une campagne marketing complète pour AET.",ressource:{titre:"Prompts professionnels marketing",url:"https://academy.openai.com/en/public/clubs/work-users-ynjqu/resources/prompting"}},
  {n:17,niv:3,titre:"IA et entrepreneuriat",objectif:"Utiliser l'IA pour structurer une idée d'activité.",retenir:["Problème","Client","Offre","Modèle économique","Acquisition","Opérations"],prompt:"Agis comme un conseiller en création d'entreprise. À partir de mon idée, identifie le problème client, la cible, l'offre, les hypothèses à tester et les premières actions. Distingue les faits fournis des hypothèses.",exercice:"Transforme une idée en offre structurée avec plan d'action 30 jours.",ressource:{titre:"Usage responsable de l'IA",url:"https://openai.com/academy/ai-fundamentals/"}},

  {n:18,niv:4,titre:"Prompting avancé",objectif:"Concevoir des instructions multi-étapes avec critères de qualité.",retenir:["Tâches complexes","Étapes","Exemples","Critères","Vérification","Révision"],prompt:"Agis comme analyste. 1) reformule l'objectif, 2) liste les informations manquantes, 3) analyse les données fournies, 4) distingue faits et hypothèses, 5) produis le résultat dans le format demandé, 6) termine par une section « À vérifier ».",exercice:"Crée un prompt d'analyse avec point de contrôle qualité intégré.",ressource:{titre:"Guide de prompting et itération",url:"https://academy.openai.com/en/public/clubs/work-users-ynjqu/resources/prompting"}},
  {n:19,niv:4,titre:"Concevoir un assistant spécialisé",objectif:"Créer un cahier des charges d'assistant IA.",retenir:["Mission","Public","Contexte","Règles","Entrées","Sorties","Limites"],prompt:"Conçois les instructions d'un assistant spécialisé en [DOMAINE]. Définis sa mission, son public, les informations qu'il peut utiliser, les règles qu'il doit respecter, son format de sortie et les situations où il doit demander une clarification.",exercice:"Conçois un assistant commercial, un assistant formateur ou un assistant support.",ressource:{titre:"Fondamentaux, workflows et agents",url:"https://academy.openai.com/"}},
  {n:20,niv:4,titre:"Workflows reproductibles",objectif:"Transformer une tâche répétitive en processus documenté.",retenir:["Déclencheur","Entrées","Étapes","Sorties","Contrôles","Responsable"],prompt:"Décris un workflow reproductible pour traiter une demande client. Donne : déclencheur, entrée, étapes, outils, sortie, contrôle humain et critères de réussite.",exercice:"Documente un workflow : document → résumé → rapport.",ressource:{titre:"Workflows reproductibles et agents",url:"https://openai.com/academy/"}},
  {n:21,niv:4,titre:"Automatisation",objectif:"Identifier ce qui peut être assisté ou automatisé sans perdre le contrôle humain.",retenir:["Tâches répétitives","Règles","Déclencheurs","Exceptions","Validation"],prompt:"Analyse mon processus de travail. Classe chaque tâche en : manuel, assisté par IA, automatisable avec validation, ou nécessitant un humain. Justifie chaque classement.",exercice:"Cartographie une activité et identifie 5 automatisations possibles.",ressource:{titre:"Workflows et agents sous supervision humaine",url:"https://help.openai.com/fr-fr/articles/20001270-cours-openai-academy"}},
  {n:22,niv:4,titre:"Vérification, sécurité et qualité",objectif:"Apprendre à contrôler les sorties de l'IA.",retenir:["Vérification factuelle","Sources","Incertitude","Confidentialité","Biais","Validation humaine"],prompt:"Audite ta réponse précédente. Liste les affirmations factuelles, indique lesquelles nécessitent une vérification externe, signale les hypothèses et propose une checklist de contrôle avant publication.",exercice:"Audite une réponse IA et construis une checklist de contrôle.",ressource:{titre:"Usage responsable de l'IA",url:"https://openai.com/academy/ai-fundamentals/"}},
  {n:23,niv:4,titre:"Projet final professionnel",objectif:"Construire et présenter un système ou projet IA complet.",retenir:["Problème","Solution","Prompts","Workflow","Livrables","Contrôles","Démonstration"],prompt:"Agis comme mon coach de projet. Aide-moi à définir un projet IA professionnel. Commence par clarifier le problème, puis propose l'architecture du workflow, les prompts, les points de contrôle, les livrables et les critères d'évaluation.",exercice:"Construis un projet complet : assistant, campagne, système de contenu ou workflow métier.",ressource:{titre:"Workflows, agents et mise en pratique",url:"https://academy.openai.com/"}},
];

const AET_NIVEAUX = {
  1:{titre:"Initiation à l'IA",couleur:"#10B981",emoji:"🟢",duree:"4 semaines",resultat:"Utiliser correctement les assistants IA"},
  2:{titre:"Maîtrise du prompting",couleur:"#F5C400",emoji:"🟡",duree:"4 semaines",resultat:"Construire et améliorer des prompts"},
  3:{titre:"IA professionnelle",couleur:"#1677FF",emoji:"🔵",duree:"6 semaines",resultat:"Appliquer l'IA aux études, au travail, au contenu et au business"},
  4:{titre:"Maîtrise",couleur:"#E23744",emoji:"🔴",duree:"6 semaines",resultat:"Workflows, assistants IA et automatisation"},
};

const AET_PROMPTS = [
  {titre:"Expliquer un sujet à un débutant",cat:"Études",desc:"Pédagogie progressive avec exercice de vérification.",prompt:"Explique [SUJET] à un débutant. Donne une définition simple, trois exemples, une analogie et un mini-exercice. Termine par 5 questions de vérification."},
  {titre:"Résumer un document",cat:"Productivité",desc:"Résumé structuré avec éléments à vérifier.",prompt:"Résume le document fourni en [N] points. Sépare les faits importants, les décisions, les chiffres et les éléments à vérifier."},
  {titre:"Corriger un texte",cat:"Études",desc:"Correction + version professionnelle.",prompt:"Corrige ce texte sans changer mon intention. Indique d'abord les principales erreurs, puis donne une version corrigée et une version plus professionnelle."},
  {titre:"Rédiger un email professionnel",cat:"Travail",desc:"Email calibré en ton et en longueur.",prompt:"Rédige un email professionnel à [DESTINATAIRE] concernant [SUJET]. Ton : [TON]. Longueur : [N] mots maximum. Termine par une demande d'action claire."},
  {titre:"Analyse marketing",cat:"Marketing",desc:"Positionnement et angles publicitaires.",prompt:"Agis comme expert marketing. Analyse [PRODUIT], [CIBLE] et [PROBLÈME]. Propose un positionnement, trois angles publicitaires et cinq idées de contenu."},
  {titre:"Publications réseaux sociaux",cat:"Réseaux sociaux",desc:"Série de posts prêts à publier.",prompt:"Crée [N] publications pour [PLATEFORME] autour de [THÈME]. Pour chaque publication : accroche, contenu, CTA et idée visuelle."},
  {titre:"Analyser une idée de business",cat:"Business",desc:"Structure client / offre / hypothèses.",prompt:"Analyse cette idée de business : [IDÉE]. Identifie client cible, problème, offre, hypothèses, risques et premières actions. Distingue faits et hypothèses."},
  {titre:"Analyser des données",cat:"Analyse",desc:"Résumé, tendances, anomalies, recommandations.",prompt:"Analyse [DOCUMENT/DONNÉES]. Donne : résumé, tendances, anomalies, limites, hypothèses et recommandations. Signale ce qui nécessite une vérification."},
  {titre:"Cadrer un projet",cat:"Productivité",desc:"Plan en étapes avec livrables.",prompt:"Aide-moi à construire [PROJET]. Commence par poser les questions indispensables, puis propose un plan en étapes avec livrables et critères de réussite."},
  {titre:"Contrôle qualité d'une réponse IA",cat:"Analyse",desc:"Audit exactitude / clarté / risques.",prompt:"Évalue la réponse précédente selon : exactitude, pertinence, clarté, respect des contraintes et risques. Identifie les faiblesses et propose une correction."},
  {titre:"Prompt d'image publicitaire",cat:"Images",desc:"Brief visuel complet et reproductible.",prompt:"Crée un prompt d'image pour une publicité [MARQUE] : sujet principal, décor, composition, lumière, cadrage, style photographique, texte à éviter dans l'image et format [FORMAT]."},
  {titre:"Script vidéo 30 secondes",cat:"Vidéo",desc:"Structure accroche / scènes / CTA.",prompt:"Transforme cette idée en vidéo de 30 secondes. Donne : accroche 0-3s, scène 1, scène 2, scène 3, voix off, texte à l'écran et appel à l'action."},
  {titre:"Cahier des charges d'un assistant IA",cat:"Programmation",desc:"Spécification d'un assistant spécialisé.",prompt:"Conçois les instructions d'un assistant spécialisé en [DOMAINE]. Définis sa mission, son public, les règles qu'il doit respecter, son format de sortie et les situations où il doit demander une clarification."},
  {titre:"Plan d'action entrepreneurial",cat:"Entrepreneuriat",desc:"Idée → offre → premières actions.",prompt:"Agis comme un conseiller en création d'entreprise. À partir de mon idée, identifie le problème client, la cible, l'offre, les hypothèses à tester et les premières actions."},
];

const AET_VIDEOS = [
  {titre:"AI Fundamentals",cat:"Débutant",niveau:"Niveau 1",desc:"Fondamentaux de l'IA et usage responsable.",url:"https://openai.com/academy/ai-fundamentals/"},
  {titre:"Introduction to Prompt Engineering",cat:"Prompting",niveau:"Niveau 1-2",desc:"Vidéo d'introduction pour les bases du prompt engineering.",url:"https://academy.openai.com/public/videos/introduction-to-prompt-engineering-2025-02-13"},
  {titre:"Mastering Prompts",cat:"Prompting",niveau:"Niveau 2",desc:"Formulation de prompts efficaces.",url:"https://academy.openai.com/en/public/videos/mastering-prompts-the-key-to-getting-what-you-need-from-chatgptmastering-prompts-the-key-to-getting-what-you-need-from-chatgpt-2025-03-20"},
  {titre:"Power Prompting",cat:"Prompting",niveau:"Niveau 2-4",desc:"Rôle, tâche, contexte, sortie, limites et vérification.",url:"https://academy.openai.com/en/public/clubs/news-organizations-b9osl/videos/power-prompting-2026-07-07"},
  {titre:"Prompting with Purpose",cat:"ChatGPT",niveau:"Niveau 2",desc:"Bonnes pratiques et techniques avancées d'itération.",url:"https://academy.openai.com/public/events/prompting-with-purpose-best-practice-techniques-for-harnessing-chatgpt-d8kbsplbun"},
  {titre:"OpenAI Academy — Prompting",cat:"ChatGPT",niveau:"Tous niveaux",desc:"Guide pratique avec exemples pour le travail et les études.",url:"https://academy.openai.com/en/public/clubs/work-users-ynjqu/resources/prompting"},
  {titre:"Gemini — outils d'apprentissage",cat:"Gemini",niveau:"Niveau 3",desc:"Utiliser Gemini pour apprendre et créer des quiz.",url:"https://support.google.com/gemini/answer/16448384?co=GENIE.Platform%3DAndroid&hl=fr"},
  {titre:"Gemini — génération de vidéos",cat:"Vidéo",niveau:"Niveau 3",desc:"Guide officiel sur la génération de vidéos dans Gemini.",url:"https://support.google.com/gemini/answer/16126339?co=GENIE.Platform%3DAndroid&hl=en"},
  {titre:"Anthropic — Prompting best practices",cat:"Automatisation",niveau:"Niveau 2-4",desc:"Techniques de prompting et templates réutilisables.",url:"https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/prompt-templates-and-variables"},
];
